spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: user_service
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: TechSpecJavaSpringFinalV2Application
  logging:
    level:
      root: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

